### ISSUE TITLE
sddm.conf file is located in /usr/lib/sddm/sddm.conf.d/

### ISSUE THREAD

**Issue by niyakipham** [FireStreaker2/Gura-SDDM#1]
![image](https://github.com/user-attachments/assets/a1b4f1e2-d551-4f6e-b640-38318bfefbd4)

**Comment by FireStreaker2** [comment]
sorry, what does this have to do with anything?

**Comment by FireStreaker2** [comment]
closing as stale, feel free to make another issue if an actual issue occurs !
